name: Docker pull

on:
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker pull
        run: docker pull tmvdl/java -a
